import { ArrowRight, CalendarDays, CircleAlert, RotateCcw } from 'lucide-react';
import { StatusBadge, statusTone } from '../../components/StatusBadge';
import { useMigrationWaves, useMigrationWorkItems } from '../../hooks/use-migration-data';

export function MigrationOverview() {
  const query = useMigrationWaves();
  const itemsQuery = useMigrationWorkItems();
  if (query.isLoading || itemsQuery.isLoading) return <div className="page-state" role="status">Loading migration plan…</div>;
  if (query.isError || itemsQuery.isError || !query.data || !itemsQuery.data) return <div className="page-state error-state" role="alert"><CircleAlert size={18} /> Migration plan could not be loaded. <button className="text-button" onClick={() => { void query.refetch(); void itemsQuery.refetch(); }}>Retry</button></div>;

  return <div className="page-stack">
    <div className="demo-notice"><CircleAlert size={15} /> Plan details below are illustrative demo records. Execution controls are unavailable until a backend contract is connected.</div>
    <section className="panel plan-summary"><div><span className="eyebrow">Migration program</span><h2>Northstar cloud transition</h2><p>Dependency-aware waves · snapshot from the demo adapter</p></div><div className="summary-stat"><span>Plan status</span><StatusBadge tone="info">In progress</StatusBadge></div><div className="summary-stat"><span>Planned resources</span><strong>{query.data.reduce((sum, wave) => sum + wave.assetCount, 0)}</strong></div><div className="summary-stat"><span>Completed</span><strong>{query.data.reduce((sum, wave) => sum + wave.completed, 0)}</strong></div></section>
    <section className="panel plan-table-panel"><div className="panel-heading"><div><p className="eyebrow">Sequence and readiness</p><h2>Wave schedule</h2></div><span className="panel-caption">Planning and execution status shown separately</span></div>
      <div className="wave-cards">{query.data.map((wave, index) => {
        const percent = wave.assetCount ? Math.round((wave.completed / wave.assetCount) * 100) : 0;
        return <article className="wave-card" key={wave.id}><div className="wave-card-top"><span className="wave-number">WAVE {String(index + 1).padStart(2, '0')}</span><StatusBadge tone={statusTone(wave.status)}>{wave.status}</StatusBadge></div><h3>{wave.name}</h3><p className="wave-strategy">{wave.strategy}</p><div className="wave-detail-grid"><div><span>Resources</span><strong>{wave.assetCount}</strong></div><div><span>Completed</span><strong>{wave.completed} <small>({percent}%)</small></strong></div><div><span>Risk</span><StatusBadge tone={statusTone(wave.risk)}>{wave.risk}</StatusBadge></div><div><span>Target start</span><strong className="wave-date"><CalendarDays size={13} /> {wave.startDate}</strong></div></div><div className="progress-line"><span style={{ width: `${percent}%` }} /></div><button className="wave-card-link" disabled title="Wave details require a connected migration API">View wave details <ArrowRight size={14} /></button></article>;
      })}{query.data.length === 0 && <div className="empty-state"><CalendarDays size={20} /><strong>No migration waves available</strong><span>Wave sequencing will appear when a migration plan is returned.</span></div>}</div>
    </section>
    <section className="panel planning-items-panel"><div className="panel-heading"><div><p className="eyebrow">Dependency-aware sequencing</p><h2>Workload migration items</h2></div><span className="panel-caption">Prerequisites and rollback points from sample plan</span></div><div className="table-scroll"><table><thead><tr><th scope="col">Workload / source → target</th><th scope="col">Wave / strategy</th><th scope="col">Dependencies</th><th scope="col">Prerequisites</th><th scope="col">Status / risk</th><th scope="col">Duration</th><th scope="col">Rollback checkpoint</th></tr></thead><tbody>{itemsQuery.data.map((item) => { const wave = query.data.find((candidate) => candidate.id === item.waveId); return <tr key={item.id}><td><strong className="table-primary">{item.name}</strong><small className="cell-subline">{item.source} → {item.target}</small>{item.criticalPath && <small className="critical-path-tag">Critical path</small>}</td><td><strong className="table-primary">{wave?.name ?? item.waveId}</strong><small className="cell-subline">{item.strategy}</small></td><td>{item.dependencies.length ? item.dependencies.join(', ') : 'None listed'}</td><td className="planning-list-cell">{item.prerequisites.join(' · ')}</td><td><StatusBadge tone={statusTone(item.status)}>{item.status}</StatusBadge><small className="cell-subline">{item.risk} risk</small></td><td>{item.estimatedDurationDays} days</td><td className="planning-list-cell">{item.rollbackCheckpoint}</td></tr>; })}{itemsQuery.data.length === 0 && <tr><td className="empty-cell" colSpan={7}>No migration work items available.</td></tr>}</tbody></table></div></section>
    <section className="panel rollback-panel"><div className="rollback-icon"><RotateCcw size={17} /></div><div><h3>Rollback checkpoints</h3><p>Sample checkpoints are documented per work item. No rollback execution action is connected.</p></div></section>
  </div>;
}
